name = "cf-agents-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV_PREFS"
id = "3adcdb80102d45d2a4f1b9eb8768da25"
preview_id = "3a60d61f2e2045309c78a089d3a901f7"

[[d1_databases]]
binding = "DB"
database_name = "agents_db"
database_id = "bebcdcd6-67b5-4ec6-8ca6-b60650d98c37"

[[vectorize]]
binding = "VEC"
index_name = "agents-memory"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]

[observability.logs]
enabled = true

[placement]
mode = "smart"
